language: python
#os:
#  - linux
#  - osx
python:
  - "2.7"
  - "3.5"
install:
  - pip install pip --upgrade
  - pip install -q -r requirements.txt --upgrade
  - conda install ruamel.yaml requests
  - conda update --all --yes
  - conda install --yes conda-build anaconda-client
before_script:
  - anaconda login --username $ANACONDA_USER --password $ANACONDA_PASSWORD
script: invoke build_all
notifications:
  email:
    recipients:
      - shyuep@gmail.com
    on_success: change
    on_failure: always
