package:
  name: bader
  version: "0.9.5"

source:
  url: http://theory.cm.utexas.edu/henkelman/code/bader/download/bader.tar.gz

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - gcc # [linux]

test:
  commands:
    - bader -h

about:
  home: http://theory.cm.utexas.edu/henkelman/code/bader
  license: MIT
  summary: Bader charge analysis library of the Henkelman group
