package:
  name: latexcodec
  version: "1.0.4"

source:
  fn: latexcodec-1.0.4.tar.gz
  url: https://pypi.python.org/packages/3e/a3/d86746a4fbafd8126a0e5c497179be8820a78a40321634dcef3994a73e80/latexcodec-1.0.4.tar.gz
  md5: 72010ec2a55227a5802239cff6fd32d6
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - latexcodec = latexcodec:main
    #
    # Would create an entry point called latexcodec that calls latexcodec.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six >=1.4.1

  run:
    - python
    - six >=1.4.1

test:
  # Python imports
  imports:
    - latexcodec

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mcmtroffaes/latexcodec
  license: MIT License
  summary: 'A lexer and codec to work with LaTeX code in Python.'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
