{% set name = "pymatgen-diffusion" %}
{% set version = "0.2.0" %}
{% set md5 = "64a1f2f5e8852ae8a170968643a55fd7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  script: python setup.py install --single-version-externally-managed --record record.txt
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pymatgen >=4.4.11
    - monty >=0.9.6

test:
  imports:
    - pymatgen_diffusion
    - pymatgen_diffusion.aimd
    - pymatgen_diffusion.neb

about:
  home: https://github.com/materialvirtuallab/pymatgen-diffusion/
  license: BSD License
  summary: 'Add-on to pymatgen for diffusion analysis.'
  license_family: BSD
