{% set name = "tabulate" %}
{% set version = "0.7.5" %}
{% set md5 = "576e1f063b8e74dbfeda02d978564987" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  noarch_python: True
  entry_points:
    - tabulate = tabulate:_main
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  commands:
    - tabulate --help

about:
  home: https://bitbucket.org/astanin/python-tabulate
  license: MIT License
  summary: 'Pretty-print tabular data'
  license_family: MIT
