package:
  name: seekpath
  version: "1.1.0"

source:
  fn: seekpath-1.1.0.tar.gz
  url: https://pypi.python.org/packages/9a/6a/cbe89455943f3bacb96beff524a06260850cf0b02cfc3c98d49b0971940a/seekpath-1.1.0.tar.gz
  md5: 6dba94cba2313c6e17fdb9f6b8a1fad3
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - seekpath = seekpath:main
    #
    # Would create an entry point called seekpath that calls seekpath.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.0
    - spglib >=1.9.4
    - future >=0.15

  run:
    - python
    - numpy >=1.0
    - spglib >=1.9.4
    - future >=0.15

test:
  # Python imports
  imports:
    - seekpath
    - seekpath.brillouinzone
    - seekpath.hpkot

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/giovannipizzi/seekpath
  license: MIT License
  summary: 'A module to obtain and visualize k-vector coefficients and obtain band paths in the Brillouin zone of crystal structures'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
