{% set name = "spglib" %}
{% set version = "1.9.8.20" %}
{% set md5 = "f33e3eff42b73d730952eba266cd01282672e0dd93b985f89eedd3af91632e4e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ md5 }}

build:
  skip: true  # [win and py<35]
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

test:
  imports:
    - spglib

about:
  home: http://atztogo.github.io/spglib/
  license: MIT
  summary: 'This is the spglib module.'
  license_family: MIT
