package:
  name: spglib
  version: "1.9.8.15"

source:
  fn: spglib-1.9.8.15.tar.gz
  url: https://pypi.python.org/packages/0a/e9/f09442f8c13e77fca9d6d16a92bd56ac9ef3434f4263f0eba354d3ed2d07/spglib-1.9.8.15.tar.gz
  md5: 68d9756273f5a8af6bcc12c14e029f7b
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - spglib = spglib:main
    #
    # Would create an entry point called spglib that calls spglib.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - spglib

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://atztogo.github.io/spglib/
  license: MIT
  summary: 'This is the spglib module.'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
