{% set name = "custodian" %}
{% set version = "1.0.3" %}
{% set md5 = "2bc54f94d4c6d2aac9fd59b7f8948fd8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  noarch_python: True
  number: 0
  entry_points:
    - cstdn = custodian.cli.cstdn:main
    - run_vasp = custodian.cli.run_vasp:main
    - run_nwchem = custodian.cli.run_nwchem:main
    - converge_kpoints = custodian.cli.converge_kpoints:main
    - converge_geometry = custodian.cli.converge_geometry:main
  script: python setup.py install --single-version-externally-managed --record record.txt
  
requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - monty >=0.9.0
    - six
    - pyyaml >=3.12

test:
  imports:
    - custodian
    - custodian.ansible
    - custodian.cli
  commands:
    - cstdn --help

about:
  home: https://github.com/materialsproject/custodian
  license: MIT License
  summary: 'A simple JIT job management framework in Python.'
  license_family: MIT
