package:
  name: enumlib
  version: 1.0

build:
  number: 1

requirements:
  build:
    - git
    - gcc # [linux]
    - m2w64-gcc-fortran # [win]
    - make # [win]

#test:
#  commands:
#    - enum.x

about:
  home: https://github.com/msg-byu/enumlib
  license: MIT
  summary: Enumlib of Gus Hart
