package:
  name: monty
  version: "0.9.6"

source:
  fn: monty-0.9.6.tar.gz
  url: https://pypi.python.org/packages/53/61/b42d8ed8d28ee5ebd4dd3dce315e1e5176f70a138c869b15e2cc6f1ef468/monty-0.9.6.tar.gz
  md5: 406ea69fdd112feacfdf208624d56903
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - monty = monty:main
    #
    # Would create an entry point called monty that calls monty.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  # Python imports
  imports:
    - monty
    - monty.os

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/materialsvirtuallab/monty
  license: MIT License
  summary: 'Monty is the missing complement to Python.'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
